### ISSUE TITLE
KeyError: 'state_dict' when running inference.py

### ISSUE THREAD

**Issue by 0801130205** [jfzhang95/pytorch-video-recognition#10]
Traceback (most recent call last):
  File "inference.py", line 77, in <module>
    main()
  File "inference.py", line 32, in main
    model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'

**Comment by mkrest** [comment]
I met the same issue, can this be solved somehow? As far as I understand from issue #8 , one should train the model again and then load model's weights. Not very useful to be honest.

Kind of new in pytorch, so please let me know if I get this wrong.
