### ISSUE TITLE
train_test_split on ucf 101 dataset

### ISSUE THREAD

**Issue by kjunhwa** [jfzhang95/pytorch-video-recognition#16]
Hi. Thank you for your uploading code.

I have a question in the dataset.py code.

As I know, ucf101 dataset have train/test list file, but in that code it divided by train_test_split by random.

So, it may cause the overlap problem in train / test dataset.

How do you think about this problem?

**Comment by wave-transmitter** [comment]
Hi, this issue is similar to #14. As noted in [UCF101](http://crcv.ucf.edu/data/UCF101.php) official website:

>  It is very important to keep the videos belonging to the same group seperate in training and testing. Since the videos in a group are obtained from single long video, sharing videos from same group in training and testing sets would give high performance.

I think this is the reason why the random split approach achieved such high performance.

**Comment by jfzhang95** [comment]
Yes, I just split dataset using sklearn package, leading to a very high performance. 
You may download official train/test lists and rewrite a dataloader to load official train and test sets.

**Comment by kjunhwa** [comment]
@wave-transmitter @jfzhang95  

Thank you so much.
