### ISSUE TITLE
Is your pre-training model trained through the UCF101 database?

### ISSUE THREAD

**Issue by Xjunjiang** [jfzhang95/pytorch-video-recognition#19]
Hi, we got an incredible result from the pre-training model you provided. Is your pre-training model from the UCF101 database?

**Comment by kamata1729** [comment]
I encountered the same problem, when I validated UCF101 with the pre-trained model, I got 0.0018527095877721167 acc.

**Comment by libb999** [comment]
> I encountered the same problem, when I validated UCF101 with the pre-trained model, I got 0.0018527095877721167 acc.

could you solve it?
