### ISSUE TITLE
out of memory?

### ISSUE THREAD

**Issue by goforfar** [jfzhang95/pytorch-video-recognition#27]
Hi! I try the code with TITANXp 12Gb, but before it starts training, it reported that "Runtimerror: cuda out of memory".
Do your guys meet the same issues?
Could anyone give some ideas for me.....Thanks

**Comment by cantonioupao** [comment]
I had the same issue with one of my projects.
Try to follow these steps:
1.Check if you are actually using your GPU and not the CPU
2. Check if the TitanXp is carrying out the training bu using the "nvidia-smi" command 
3. If everything is working fine, then try reducing the batch size and the number of epochs

**Comment by goforfar** [comment]
> I had the same issue with one of my projects.
> Try to follow these steps:
> 1.Check if you are actually using your GPU and not the CPU
> 2. Check if the TitanXp is carrying out the training bu using the "nvidia-smi" command
> 3. If everything is working fine, then try reducing the batch size and the number of epochs

I have tried your steps but it reported 'out of memory' issues again even with the batch size of 5.......
Have u try the code?Could u give some help to me in details

**Comment by goforfar** [comment]
> I had the same issue with one of my projects.
> Try to follow these steps:
> 1.Check if you are actually using your GPU and not the CPU
> 2. Check if the TitanXp is carrying out the training bu using the "nvidia-smi" command
> 3. If everything is working fine, then try reducing the batch size and the number of epochs

And I have no idea which variable cause the memory explosion...
the picture is the shot of my try of the code with a small dataset and a batch size of 5....

**Comment by goforfar** [comment]
![IMG_20190506_231625](https://user-images.githubusercontent.com/44395406/57238634-7a241d00-705c-11e9-90b5-e5b61fda8f66.jpg)

**Comment by goforfar** [comment]
It's something wrong with my libraries.I failed to try it with win10 but can run with ubuntu..

Thank @cantonioupao , you give me a lot of advice.
