### ISSUE TITLE
how to pre-processing data?

### ISSUE THREAD

**Issue by libb999** [jfzhang95/pytorch-video-recognition#36]
how to pre-processing video to img ?
thank you

**Comment by Hongbo-Miao** [comment]
I downloaded video, and then got same question. To save some time for future people:

As readme:

> 2. Download pretrained model from [BaiduYun](https://pan.baidu.com/s/1saNqGBkzZHwZpG-A5RDLVw) or 
> [GoogleDrive](https://drive.google.com/file/d/19NWziHWh1LgCcHU34geoKwYezAogv9fX/view?usp=sharing).
>    Currently only support pretrained model for C3D.

So we should download pretrained images directly.

**Comment by hongbo-miao** [comment]
To save some time for future people, I wrote the way at https://github.com/jfzhang95/pytorch-video-recognition/issues/60
