### ISSUE TITLE
Method to pre-process video to images

### ISSUE THREAD

**Issue by hongbo-miao** [jfzhang95/pytorch-video-recognition#60]
I met this issue, after searching but I didn't find solutions in these tickets:
https://github.com/jfzhang95/pytorch-video-recognition/issues/36
https://github.com/jfzhang95/pytorch-video-recognition/issues/52

To save some time for future people, here is the method:

1. Take UCF101 for example, download the dataset at 
https://www.crcv.ucf.edu/data/UCF101/UCF101.rar

2. Update 
https://github.com/jfzhang95/pytorch-video-recognition/blob/master/mypath.py
to point to correct dataset and model paths like

```py
class Path(object):
    @staticmethod
    def db_dir(database):
        if database == 'ucf101':
            # folder that contains class labels
            root_dir = '/Users/hongbo-miao/pytorch-video-recognition/datasets/UCF-101'

            # Save preprocess data into output_dir
            output_dir = '/Users/hongbo-miao/pytorch-video-recognition/datasets/ucf101'

            return root_dir, output_dir
        elif database == 'hmdb51':
            # folder that contains class labels
            root_dir = '/Users/hongbo-miao/pytorch-video-recognition/datasets/hmdb-51'

            output_dir = '/Users/hongbo-miao/pytorch-video-recognition/datasets/hmdb51'

            return root_dir, output_dir
        else:
            print('Database {} not available.'.format(database))
            raise NotImplementedError

    @staticmethod
    def model_dir():
        return '/Users/hongbo-miao/pytorch-video-recognition/models/c3d-pretrained.pth'
```

Search all places and replace from `pretrained=True` to `pretrained=False`.

4. Run `python train.py`, then you will see it starts to pre process
![image](https://user-images.githubusercontent.com/3375461/117508730-a5c79e00-afbb-11eb-8375-ce1bb14d3063.png)

Once pre-processing done, it will start to train.

**Comment by xiehewei** [comment]
Can you show me your directory tree and dataset structure？I always encounter such mistakes。
![image](https://user-images.githubusercontent.com/51471231/129597264-8e785b06-d3f4-4292-b263-d9457937a5a2.png)

**Comment by xiehewei** [comment]
Why?
![image](https://user-images.githubusercontent.com/51471231/129597431-743fceb7-a882-41a7-84d2-5c946c5c8d48.png)

**Comment by hongbo-miao** [comment]
Hi @xiehewei151782 it has been a long time I was working on it. I cannot really remember.
The doc I wrote here worked for me at that moment to set up this repo.

Our team repo is at https://github.com/stanford-action-recognition/ar . Hope the info there can help you go further! 😃

**Comment by 282517bjiMNqwewed** [comment]
> 你能给我看看你的目录树和数据集结构吗？我总是遇到这样的错误。 ![图像](https://user-images.githubusercontent.com/51471231/129597264-8e785b06-d3f4-4292-b263-d9457937a5a2.png)
哈喽，我也遇到类似问题，请问你最后怎么解决的呢

**Comment by Wangdanchunbufuz** [comment]
> Why? ![image](https://user-images.githubusercontent.com/51471231/129597431-743fceb7-a882-41a7-84d2-5c946c5c8d48.png)

你好，我也遇到了这样的问题，请问您是怎样解决的呢？
![image](https://github.com/jfzhang95/pytorch-video-recognition/assets/92201550/dcb72b56-80ef-4b43-be32-4ac6f72d0b56)

**Comment by Wangdanchunbufuz** [comment]
> Why? ![image](https://user-images.githubusercontent.com/51471231/129597431-743fceb7-a882-41a7-84d2-5c946c5c8d48.png)

你好，我也遇到了这样的问题，请问您是怎样解决的呢？
![image](https://github.com/jfzhang95/pytorch-video-recognition/assets/92201550/90726152-ff00-4414-83a7-fa0fee6cfc05)

**Comment by 282517bjiMNqwewed** [comment]
好像是把某个代码中的false改成true。您可以网上搜一下这个代码复现，还挺多的



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 15, 2024 21:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jfzhang95/pytorch-video-recognition] Method to pre-process videoto images (#60)




  
Why? 
  
你好，我也遇到了这样的问题，请问您是怎样解决的呢？
 image.png (view on web)

**Comment by Wangdanchunbufuz** [comment]
> 好像是把某个代码中的false改成true。您可以网上搜一下这个代码复现，还挺多的
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jan 15, 2024 21:58 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [jfzhang95/pytorch-video-recognition] Method to pre-process videoto images (#60) Why? 你好，我也遇到了这样的问题，请问您是怎样解决的呢？ image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢，根据你的提示我解决了这个问题！十分感谢

**Comment by Wangdanchunbufuz** [comment]
请问是否有遇到过卡在这里不训练的情况吗？
![image](https://github.com/jfzhang95/pytorch-video-recognition/assets/92201550/dd7fe162-32ad-4b98-8ef6-f4b1df6ae9bb)
