### ISSUE TITLE
Pre-trained model not downloading because login required

### ISSUE THREAD

**Issue by milestonezero** [jfzhang95/pytorch-video-recognition#8]
Can you please send me any other link of your pre-trained model. Because i am not in china and i can't login to baidu App.
Thanks

**Comment by jfzhang95** [comment]
Hi,
Thank you for your interest in this code. Pretrained model could be found in [Goole Drive](https://drive.google.com/file/d/19NWziHWh1LgCcHU34geoKwYezAogv9fX/view?usp=sharing) now.

**Comment by milestonezero** [comment]
Thank You so much.

**Comment by jfzhang95** [comment]
Sorry, I do not have fully trained models currently. Previous trained models were save on another computer which I cannot reach now. So I suggest you train these models by yourself.
